future: true
permalink: /:title/
title: Encontrando Online

# =========================================================
# =========================================================
links_globais:
  - nome: "Formula Negocio Online - Como usar a internet para aumentar vendas"
    url: "https://go.hotmart.com/K9133139A"
  - nome: "Pack Canva Profissional – Milhares de posts editáveis para divulgar sua empresa"
    url: "https://go.hotmart.com/G55484998X"

    
# _config.yml — SITEMAP COM SOMENTE POSTS + HOMEPAGE

url: "https://encontrando.online"
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag   # opcional, mas recomendado

# =================================================
# SITEMAP: só homepage + posts (nada mais)
# =================================================
defaults:
  -
    scope:
      path: ""                # tudo no site
    values:
      sitemap: false          # padrão = não entra
  -
    scope:
      path: ""                # página inicial (index.md ou index.html)
      type: pages
    values:
      sitemap: true           # entra sim
  -
    scope:
      path: "_posts"          # pasta dos posts
    values:
      sitemap: true           # entra sim
